### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [jkennethcarino/AnkiEditor#6]
Hi,

Since this app is GNU GPL v3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by nicolasmaia** [comment]
@jkennethcarino FYI, it's ready to be built, it just needs your permission https://gitlab.com/fdroid/rfp/issues/616

**Comment by PanderMusubi** [comment]
@jkennethcarino Do you support the request for package at F-Droid?

**Comment by IzzySoft** [comment]
I guess no answer means @jkennethcarino is not opposed, and we can take that as "agreement" it is OK with him.
